# Funding platforms for Eleanor
# These are the platforms where people can sponsor this project

github: [Project-Eleanor]
# patreon:
# open_collective: eleanor
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
custom:
